version: "3.8"

services:
   nextjs-app:
      build: .
      image: portfolio
      container_name: nextjs
      command: bash -c "npm run dev"
      volumes:
         - .:/app
      ports:
         - 80:3000
      environment:
         NODE_ENV: development
